### ISSUE TITLE
CT100: Manualy changing temperature in HA, raise and error (Setting temperature not allowed in this mode)

### ISSUE THREAD

**Issue by marcomsousa** [bosch-thermostat/bosch-thermostat-client-python#11]
When I change the temperature in the HC1 Climate, it really worked. But the Bosch Integration raise this error:

```
Logger: bosch_thermostat_client.circuits.nefit_circuit
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/circuits/nefit_circuit.py:76
First occurred: 14:14:37 (3 occurrences)
Last logged: 14:23:13

Setting temperature not allowed in this mode. Temperature is probably out of range MIN-MAX!
```
As I explain, it give the error message but changing the temperature really worked.

Is very posible to be related with #10, because It work without any issue the first time I restart HA.

**Comment by pszafer** [comment]
Please, check if 0.10.0 fixes this issue for you
