### ISSUE TITLE
aioxmpp library used in bosch_thermostat_client raise this issue "ValueError: only one listener allowed per matcher"

### ISSUE THREAD

**Issue by marcomsousa** [bosch-thermostat/bosch-thermostat-client-python#12]
aioxmpp library used in bosch_thermostat_client raise this issue:

> 2021-01-10 19:02:15 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/config/custom_components/bosch/__init__.py", line 276, in thermostat_refresh
> await self.component_update(SENSOR, event_time)
> File "/config/custom_components/bosch/__init__.py", line 255, in component_update
> await entity.bosch_object.update()
> File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/helper.py", line 199, in update
> result = await self._connector.get(item[URI])
> File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 99, in get
> self.register_callbacks()
> File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 50, in register_callbacks
> self.message_dispatcher.register_callback(
> File "/usr/local/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 207, in register_callback
> raise ValueError(
> ValueError: only one listener allowed per matcher

**Comment by pszafer** [comment]
Fixed in 0.10.0

**Comment by marcomsousa** [comment]
Thanks
