### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SnarfW** [bosch-thermostat/bosch-thermostat-client-python#24]
First, thank you for making this tool available. I managed to install the python client and connect to my Easycontrol. 
I would like to publish several parameters to MQTT. I wanted to do this with a Python routine. Unfortunately, I fail. 

How can I extract a specific parameter, for instance /heatSources/actualSupplyTemperature in python? 
I did have a look at “example_nefit_tc200v2.py”, but could not find the answer in here.

I would appreciate when someone could give me a hint.

**Comment by pszafer** [comment]
Hi, don't look at examples anymore as those are not up to date.
If you use Home Assistant then you can use custom component I created.
If you need python then you need to initialize BoschGateway and run query.
https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/e74a05f77684721b59cc871f46ba937c40332211/bosch_thermostat_client/bosch_cli.py#L260-L315

One thing though, you can't allow to send multiple requests at same time!

**Comment by SnarfW** [comment]
Hi, thank you for your response. I am using Openhab instead of Home Assistant, therefor I am looking for another solution. Thank you guiding me in the proper direction. I have been able to send the first parameters to mqtt.
