### ISSUE TITLE
fetch_all : TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/bosch-thermostat-client-python#31]
Trying to use `fetch_all` I get the following error 

```
File "/srv/homeassistant/lib/python3.10/site-packages/bosch_thermostat_client/sensors/energy.py", line 80, in fetch_all
    self._past_data[row["d"]] = row
TypeError: list indices must be integers or slices, not str
```
https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/dev/bosch_thermostat_client/sensors/energy.py#L80

**Comment by doudz** [comment]
https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/dev/bosch_thermostat_client/sensors/energy.py#L39

`self._past_data = [] `should be replaced by `self._past_data = {}`

**Comment by pszafer** [comment]
you're right.
