### ISSUE TITLE
New feature: MQTT support

### ISSUE THREAD

**Issue by OlliL** [bosch-thermostat/bosch-thermostat-client-python#33]
I'm currently taking the clients output, parse it with awk to generate influxdb raw-data for storing the results via HTTP into my influxdb.

I was wondering what you would think about using [paho](https://www.eclipse.org/paho/index.php?page=clients/python/index.php) to allow directly sending the retrieved data to a MQTT broker instead of stdout or file?

I would volunteer working on that. Please tell me what you think about that feature. I would go into more detail how I would integrate that into the client if you like the idea in general.

Please let me know your thoughts!

**Comment by pszafer** [comment]
I think it would be better to create extra app and use this project as lib to this app.
If you want I can create repo for you in `bosch-thermostat` organization and help you a little if you need.

**Comment by OlliL** [comment]
the idea with an extra application and using bosch-thermostat-client-python just as a lib sounds perfectly fine. It helps not bloating the current python client and concentrate the mqtt stuff in another project.

I must admit, I am no Python expert (usually working with Java in my professional job) so I have to play around a bit with it to get it going.... I'll get back once I got it generally working with app + lib and then I would like to discuss about the MQTT part.

**Comment by OlliL** [comment]
OK, I basically have a mqtt publishing client ready. At first only as a script without all the packaging around because I'd like to hear some opinions from you first :smile:

It is basically a copy of bosch_cli.py reduced by its put command and some options (like stdout, output, ignore-unknown,....) and enhanced by mqtt functionality.

# Details
- the topics it publishes will be "bosch-thermostat/_gateway.device_model_-_gateway.uuid_/_id_ so for example "bosch-thermostat/RC300-mySecretDeviceUUID/heatingCircuits/hc1/roomtemperature". Do you think the first part (bosch-thermostat) should be any different or even configurable?
- it will only publish data where a value exists. So
  - **no** data only containing references (like `/dhwCircuits`)
  - **no** data only containing multiple values (like `/heatSources/info`)
  - **no** data only containing recording (like `/recordings/dhwCircuits/dhw1/actualTemp?interval=2023-4`)
- it is no daemon, so it will not sit and wait for any data to recieve therefore it won't put any data to the thermostat

![grafik](https://user-images.githubusercontent.com/4688427/233812575-9b0a6a58-16c4-4f52-b062-b93e353cb537.png)

What do you think?

**Comment by pszafer** [comment]
for topic I'd use `bosch`, simplier and shorter. No need for configure IMO. As second part of topic I'd use uuid.
Model etc, you could put in one of topics.

Do you want to daemonize it?

**Comment by OlliL** [comment]
# Daemonize
Yeah I've implemented 2 new parameters and a function to handle it like that now:
```
[...]
    click.option(
        "--daemon",
        is_flag=True,
        required=False,
        default=False,
        help="Start as daemon.",
    ),
    click.option(
        "--interval",
        default="300",
        type=int,
        show_default=True,
        help="Specify polling interval in seconds when started as daemon.",
    ),
[...]
async def _execute(gateway, fun):
    c = click.get_current_context()
    daemon = c.params["daemon"]
    interval = c.params["interval"]

    _LOGGER.debug("Trying to connect to gateway.")
    connected = await gateway.check_connection()
    if connected:
        _LOGGER.info("Successfully connected to gateway. Found UUID: %s", gateway.uuid)
        if daemon:
            _LOGGER.info("Executing as daemon, interval is %d seconds.", interval)
            while True:
                await fun()
                _LOGGER.info("Sleeping %d seconds...", interval)
                time.sleep(interval)
        else:
            await fun()
    else:
        _LOGGER.error("Couldn't connect to gateway!")
```
Which can be used in `scan` or `query` like this:
```        await _execute(gateway, lambda: _scan(gateway, smallscan))```
or
```        await _execute(gateway, lambda: _runquery(gateway, path))```

- What I was wondering and you might be able to answer - what keep-alive-timeout has the HTTP connection to those devices? Imagine configuring an interval of like 1 hour - would that run into a problem?
- how can i test XMPP? All I'm getting is "aiosasl.common.AuthenticationFailure: user intervention: authentication failed: authentication aborted by user" from aioxmpp when choosing XMPP over HTTP

# Topics
Yeah I'm fine with just `bosch`, but I would propose to keep the model in the topic path. Its easier to recognize for a human what device it is when you going to select a topic to read from. Imagine there might be several other devices (not only thermostats) sending MQQT stuff to `bosch`. I find the way shellies are submitting their data nice:

![grafik](https://user-images.githubusercontent.com/4688427/234354194-94b1a6cf-ffe0-4d94-93e1-773c6d2f048e.png)

**Comment by OlliL** [comment]
I just pushed https://github.com/OlliL/bosch-thermostat-mqtt
Any suggestion is welcome - especially with my efforts in getting pdm packaging done and so on - I have no experience with it :smile: 

Would be cool if we could move it into this project-space here.

**Comment by OlliL** [comment]
Where you able to find some time to look into my code? :smile:

**Comment by pszafer** [comment]
Sorry for very late response....
I'd use `aiomqtt` and make it asynchronous.
