### ISSUE TITLE
CLI "put" fails due to path options handling inconsistency

### ISSUE THREAD

**Issue by jamesbulpin** [bosch-thermostat/bosch-thermostat-client-python#41]
Trying to execute e.g.:

`bosch_cli put [...] --protocol XMPP --device EASYCONTROL --path /system/awayMode/enabled false`

fails with 400 "Bad request" errors from the gateway. The log shows the following, note the tuple enclosing of the path string:

`[bosch_thermostat_client.connectors.xmpp] Sending PUT request to ('/system/awayMode/enabled',) with value true`

I believe the root cause is that the `click` options parsing in `bosch_cli.py` for the `put` command is configuring `--path` to be used multiple times (as in `--query`) but treating it like a non-multiple argument by virtue of the type used in the definition of the `put()` function:

```
_path_options = [
    click.option(
        "-p",
        "--path",
        type=str,
        required=True,
        multiple=True,
        help="Path to run against. Look at rawscan at possible paths. e.g. /gateway/uuid - Can be specified multiple times!",
    )
]
```

```
@cli.command()
@add_options(_cmd1_options)
@add_options(_path_options)
@click.argument("value", nargs=1)
@click.pass_context
@coro
async def put(
    ctx,
    host: str,
    token: str,
    password: str,
    protocol: str,
    device: str,
    path: str,    <====================
    debug: int,
    value: str,
):
```

Both `--put` and `--query` share the definition of `_path_options`. The latter defines `path` as `list[str]`:

```
@cli.command()
@add_options(_cmd1_options)
@add_options(_path_options)
@click.pass_context
@coro
async def query(
    ctx,
    host: str,
    token: str,
    password: str,
    protocol: str,
    device: str,
    path: list[str],    <====================
    debug: int,
):
```
My workaround is to change the type in the `put()` definition to `list[str]` and pass the first element from the list when calling `_runpush` (i.e. `await _runpush(gateway, path[0], value)`). This does lead to a successful put of the value to the thermostat.

A proper fix would probably be to have a separate non-multiple definition of `_path_options` for the `put` command, rather than have it share the definition with the `query` command.

bosch-thermostat-client v0.23.2 / Python 3.11.2 / click 8.1.7

**Comment by pszafer** [comment]
Fixed in v0.25.0dev
